[pytest]
asyncio_mode = auto
pythonpath =
    .
    src
    src/ticket_api/src
    src/ticket_impl/src
    src/ticket_client_adapter/src
    src/ticket_client_generated
testpaths = 
    "tests"
    "src/*/tests"
    "src/ticket_client_adapter/tests"
    "src/ticket_client_generated/tests"

addopts =
    "--cov"
    "--cov-report=term-missing"
    "--cov-report=html"
    "--cov-fail-under=90"
    "--import-mode=importlib"
    "--strict-markers"
    "-v"

markers =
    unit: Unit tests
    integration: Integration tests
    e2e: End-to-end tests
    circleci: CI/CD compatible tests
    local_credentials: Tests requiring local credentials
