from collections.abc import Iterator

from message import Message as BaseMessage

from mail_client_api import Client, Message
from src.mail_client_service_client.mail_client_api_service_client.client import Client as AutoGeneratedClient
from src.mail_client_service_client.mail_client_api_service_client.models import MessageDetail, MessageSummary


class ServiceMessage(BaseMessage):

    def __init__(self, detail: MessageDetail | MessageSummary):
        self._detail = detail

    @property
    def id(self) -> str:
        return getattr(self._detail, "id", "")

    @property
    def from_(self) -> str:
        return getattr(self._detail, "from_", "")

    @property
    def to(self) -> str:
        return getattr(self._detail, "to", "")

    @property
    def date(self) -> str:
        return getattr(self._detail, "date", "")

    @property
    def subject(self) -> str:
        return getattr(self._detail, "subject", "")

    @property
    def body(self) -> str:
        return getattr(self._detail, "body", "")


class ServiceClientAdapter(Client):

    def __init__(self, base_url: str):
        self._client = AutoGeneratedClient(base_url=base_url)

    def get_messages(self, max_results: int = 10) -> Iterator[Message]:
        resp = self._client.messages.list_messages.sync(max_results=max_results)
        for msg_summary in resp.messages:
            yield ServiceMessage(msg_summary)

    def get_message(self, message_id: str) -> Message:
        resp = self._client.messages.get_message.sync(message_id=message_id)
        return ServiceMessage(resp)

    def delete_message(self, message_id: str) -> bool:
        try:
            self._client.messages.delete_message.sync(message_id=message_id)
            return True
        except Exception:
            return False

    def mark_as_read(self, message_id: str) -> bool:
        try:
            self._client.messages.mark_as_read.sync(message_id=message_id)
            return True
        except Exception:
            return False
