from collections.abc import Iterator

from mail_client_api import Client, Message
from src.mail_client_service_client.mail_client_api_service_client.client import Client as AutoGeneratedClient
from src.mail_client_service_client.mail_client_api_service_client.models import MessageDetail, MessageSummary
from src.mail_client_service_client.mail_client_api_service_client.api.default import (
    get_messages_summary_messages_get,
    get_message_detail_messages_message_id_get,
    delete_message_messages_message_id_delete,
    mark_message_as_read_messages_message_id_mark_as_read_post,
)


class ServiceMessage(Message):
    def __init__(self, detail: MessageDetail | MessageSummary):
        self._detail = detail

    @property
    def id(self) -> str:
        return getattr(self._detail, "id", "")

    @property
    def from_(self) -> str:
        return getattr(self._detail, "from_", "")

    @property
    def to(self) -> str:
        return getattr(self._detail, "to", "")

    @property
    def date(self) -> str:
        return getattr(self._detail, "date", "")

    @property
    def subject(self) -> str:
        return getattr(self._detail, "subject", "")

    @property
    def body(self) -> str:
        return getattr(self._detail, "body", "")


class ServiceClientAdapter(Client):
    def __init__(self, base_url: str):
        self._client = AutoGeneratedClient(base_url=base_url)

    def get_messages(self, max_results: int = 10) -> Iterator[Message]:
        resp = get_messages_summary_messages_get.sync(client=self._client, max_results=max_results)
        if resp and isinstance(resp, list):
            for msg_summary in resp:
                yield ServiceMessage(msg_summary)

    def get_message(self, message_id: str) -> Message:
        resp = get_message_detail_messages_message_id_get.sync(client=self._client, message_id=message_id)
        if resp and isinstance(resp, MessageDetail):
            return ServiceMessage(resp)
        raise Exception(f"Message {message_id} not found")

    def delete_message(self, message_id: str) -> bool:
        try:
            resp = delete_message_messages_message_id_delete.sync(client=self._client, message_id=message_id)
            return resp is not None
        except Exception:
            return False

    def mark_as_read(self, message_id: str) -> bool:
        try:
            resp = mark_message_as_read_messages_message_id_mark_as_read_post.sync(client=self._client, message_id=message_id)
            return resp is not None
        except Exception:
            return False
