from typing import Any

class TestClient:
    def __init__(self, app: Any, **kwargs: Any) -> None: ...
    def __enter__(self) -> TestClient: ...
    def __exit__(self, *args: Any) -> None: ...
    def get(self, url: str, **kwargs: Any) -> Any: ...
    def post(self, url: str, **kwargs: Any) -> Any: ...
    def put(self, url: str, **kwargs: Any) -> Any: ...
    def delete(self, url: str, **kwargs: Any) -> Any: ...
    def patch(self, url: str, **kwargs: Any) -> Any: ...
    def request(self, method: str, url: str, **kwargs: Any) -> Any: ...
