import re
from collections.abc import Callable
from typing import Any, TypeVar

_F = TypeVar("_F", bound=Callable[..., Any])

class MockRouter:
    def get(self, url: str | re.Pattern[str]) -> Route: ...
    def post(self, url: str | re.Pattern[str]) -> Route: ...
    def put(self, url: str | re.Pattern[str]) -> Route: ...
    def patch(self, url: str | re.Pattern[str]) -> Route: ...
    def delete(self, url: str | re.Pattern[str]) -> Route: ...
    def __enter__(self) -> MockRouter: ...
    def __exit__(self, *args: object) -> None: ...
    def __call__(self, func: _F) -> _F: ...

class Route:
    called: bool
    calls: Any
    side_effect: Any

    def mock(
        self,
        return_value: Any = ...,
        *,
        json: Any = ...,
        content: bytes | str | None = ...,
        text: str | None = ...,
        status_code: int = ...,
        headers: dict[str, str] | None = ...,
        side_effect: Any = ...,
    ) -> Route: ...
    def respond(self, status_code: int = ..., **kwargs: Any) -> Route: ...

mock: MockRouter

def get(url: str | re.Pattern[str]) -> Route: ...
def post(url: str | re.Pattern[str]) -> Route: ...
def put(url: str | re.Pattern[str]) -> Route: ...
def patch(url: str | re.Pattern[str]) -> Route: ...
def delete(url: str | re.Pattern[str]) -> Route: ...
