import re
from collections.abc import Callable
from typing import Any, TypeVar

_F = TypeVar("_F", bound=Callable[..., Any])

class MockRouter:
    def get(self, url: str | re.Pattern[str]) -> Route: ...
    def post(self, url: str | re.Pattern[str]) -> Route: ...
    def put(self, url: str | re.Pattern[str]) -> Route: ...
    def patch(self, url: str | re.Pattern[str]) -> Route: ...
    def delete(self, url: str | re.Pattern[str]) -> Route: ...
    def __enter__(self) -> MockRouter: ...
    def __exit__(self, *args: object) -> None: ...
    def __call__(self, func: _F) -> _F: ...

class Route:
    def mock(self, return_value: Any = None) -> Route: ...
    def respond(self, status_code: int = 200) -> Route: ...

def mock() -> MockRouter: ...
def get(url: str | re.Pattern[str]) -> Route: ...
def post(url: str | re.Pattern[str]) -> Route: ...
def put(url: str | re.Pattern[str]) -> Route: ...
def patch(url: str | re.Pattern[str]) -> Route: ...
def delete(url: str | re.Pattern[str]) -> Route: ...
