"""Adapter for mail client service."""

from collections.abc import Iterator

from mail_client_api import Client, Message
from src.mail_client_service_client.mail_client_api_service_client.api.default import (
    delete_message_messages_message_id_delete,
    get_message_detail_messages_message_id_get,
    get_messages_summary_messages_get,
    mark_message_as_read_messages_message_id_mark_as_read_post,
)
from src.mail_client_service_client.mail_client_api_service_client.client import (
    Client as AutoGeneratedClient,
)
from src.mail_client_service_client.mail_client_api_service_client.models import (
    MessageDetail,
    MessageSummary,
)


class MessageNotFoundError(Exception):
    """Exception raised when a message is not found."""


class ServiceMessage(Message):
    """Service implementation of Message interface."""

    def __init__(self, detail: MessageDetail | MessageSummary) -> None:
        """Initialize ServiceMessage with message detail or summary."""
        self._detail = detail

    @property
    def id(self) -> str:
        """Get message ID."""
        return self._detail.id or ""

    @property
    def from_(self) -> str:
        """Get sender address."""
        return self._detail.from_ or ""

    @property
    def to(self) -> str:
        """Get recipient address."""
        if isinstance(self._detail, MessageDetail):
            return self._detail.to or ""
        return ""

    @property
    def date(self) -> str:
        """Get message date."""
        return self._detail.date or ""

    @property
    def subject(self) -> str:
        """Get message subject."""
        return self._detail.subject or ""

    @property
    def body(self) -> str:
        """Get message body."""
        if isinstance(self._detail, MessageDetail):
            return self._detail.body or ""
        return ""


class ServiceClientAdapter(Client):
    """Client adapter for mail service."""

    def __init__(self, base_url: str) -> None:
        """Initialize adapter with service base URL."""
        self._client = AutoGeneratedClient(base_url=base_url)

    def get_messages(self, max_results: int = 10) -> Iterator[Message]:
        """Get messages from the service."""
        resp = get_messages_summary_messages_get.sync(client=self._client, max_results=max_results)
        if resp and isinstance(resp, list):
            for msg_summary in resp:
                yield ServiceMessage(msg_summary)

    def get_message(self, message_id: str) -> Message:
        """Get a specific message by ID."""
        resp = get_message_detail_messages_message_id_get.sync(
            client=self._client,
            message_id=message_id,
            )
        if resp and isinstance(resp, MessageDetail):
            return ServiceMessage(resp)
        msg = f"Message {message_id} not found"
        raise MessageNotFoundError(msg)

    def mark_as_read(self, message_id: str) -> bool:
        """Mark a message as read."""

        try:
            mark_message_as_read_messages_message_id_mark_as_read_post.sync(
                client=self._client,
                message_id=message_id,
            )
            # 204 No Content means success, even if resp is None
            return True
        except Exception:
            return False

    def delete_message(self, message_id: str) -> bool:
        """Delete a message by ID."""
        try:
            delete_message_messages_message_id_delete.sync(
                client=self._client,
                message_id=message_id,
            )
            # 204 No Content means success, even if resp is None
            return True
        except Exception:
            return False
